const recipeCatalog = [
    {
        id: "ramen-salad",
        title: "Crunchy Ramen Salad",
        category: "Healthy",
        img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        url: "recipe-details.html?id=ramen-salad",
        reviews: "42",
        description: "A fresh, vibrant salad packed with crunchy ramen noodles, fresh cabbage, and a tangy sweet vinaigrette dressing.",
        ingredients: ["2 packages instant ramen noodles (discard seasoning)", "1 bag (14 oz) shredded coleslaw mix", "1 cup sliced almonds, toasted", "1/2 cup sunflower seeds", "3 green onions, chopped", "1/4 cup olive oil", "3 tbsp rice vinegar", "2 tbsp sugar"],
        directions: ["Crush the uncooked ramen noodles into small pieces.", "Combine noodles, coleslaw mix, almonds, sunflower seeds, and green onions in a large bowl.", "Whisk olive oil, rice vinegar, and sugar in a small jar until sugar dissolves.", "Drizzle dressing over salad right before serving and toss well."]
    },
    {
        id: "air-fryer-chicken",
        title: "Crispy Air Fryer Chicken Thighs",
        category: "Air Fryer",
        img: "https://images.unsplash.com/photo-1606755962773-d324e0a13086",
        url: "recipe-details.html?id=air-fryer-chicken",
        reviews: "128",
        description: "Perfectly seasoned chicken thighs with an incredibly crispy skin and juicy, tender center made right in your air fryer.",
        ingredients: ["4 bone-in, skin-on chicken thighs", "1 tbsp olive oil", "1 tsp garlic powder", "1 tsp onion powder", "1 tsp smoked paprika", "1/2 tsp salt", "1/4 tsp black pepper"],
        directions: ["Preheat air fryer to 380°F (193°C).", "Pat chicken thighs dry with a paper towel and coat evenly with olive oil.", "Mix seasonings in a small bowl and rub generously over the chicken.", "Place chicken skin-side down in basket and cook for 12 minutes.", "Flip skin-side up and cook for another 10-12 minutes until internal temp reaches 165°F."]
    },
    {
        id: "slow-cooker-pot-roast",
        title: "Ultimate Slow Cooker Pot Roast",
        category: "Slow Cooker",
        img: "https://images.unsplash.com/photo-1544025162-d76694265947",
        url: "recipe-details.html?id=slow-cooker-pot-roast",
        reviews: "95",
        description: "Tender, melt-in-your-mouth beef pot roast simmered low and slow all day with rich gravy, carrots, and potatoes.",
        ingredients: ["3 lb chuck roast", "1 lb baby red potatoes, halved", "4 large carrots, cut into 2-inch chunks", "1 yellow onion, wedged", "2 cups beef broth", "2 tbsp Worcestershire sauce", "2 cloves garlic, minced", "1 packet onion soup mix"],
        directions: ["Place halved potatoes, carrots, and onion wedges in the bottom of the slow cooker.", "Season chuck roast with salt and pepper, then rest it on top of the vegetables.", "Whisk beef broth, Worcestershire sauce, minced garlic, and onion soup mix together.", "Pour liquid over the roast, cover, and cook on LOW for 8 hours."]
    },
    {
        id: "tomato-basil-soup",
        title: "Creamy Tomato Basil Soup",
        category: "Soups",
        img: "https://images.unsplash.com/photo-1547592165-e1d17fed6005",
        url: "recipe-details.html?id=tomato-basil-soup",
        reviews: "64",
        description: "A rich, silky tomato soup packed with fresh basil notes—perfect for pairing with a classic grilled cheese sandwich.",
        ingredients: ["2 cans (28 oz each) crushed tomatoes", "4 tbsp unsalted butter", "1 yellow onion, finely chopped", "2 cups vegetable broth", "1/2 cup heavy cream", "1/4 cup fresh basil leaves, chopped", "Salt and pepper to taste"],
        directions: ["Melt butter in a large pot over medium heat; sauté onion until translucent.", "Add crushed tomatoes and vegetable broth; simmer for 15 minutes.", "Remove from heat and stir in heavy cream and fresh chopped basil.", "Puree soup with an immersion blender until smooth, then season to taste."]
    },
    {
        id: "classic-pepperoni-pizza",
        title: "Homemade Pepperoni Pizza",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
        url: "recipe-details.html?id=classic-pepperoni-pizza",
        reviews: "210",
        description: "Skip delivery with this easy, perfect crispy homemade pizza loaded with zesty marinara, mozzarella, and spicy pepperoni.",
        ingredients: ["1 pizza dough ball", "1/2 cup pizza sauce", "1.5 cups shredded mozzarella cheese", "1/4 cup pepperoni slices", "1 tsp dried oregano", "1 tbsp cornmeal"],
        directions: ["Preheat oven to 500°F (260°C) and dust a baking sheet with cornmeal.", "Roll pizza dough out to a 12-inch circle and transfer to the baking sheet.", "Spread pizza sauce evenly, leaving a small border for the crust.", "Top with mozzarella, pepperoni slices, and a sprinkle of dried oregano.", "Bake for 10-12 minutes until the cheese is bubbling and crust is golden brown."]
    },
    {
        id: "chocolate-chip-cookies",
        title: "Chewy Chocolate Chip Cookies",
        category: "Desserts",
        img: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e",
        url: "recipe-details.html?id=chocolate-chip-cookies",
        reviews: "340",
        description: "The gold standard of baking: thick cookies with crispy, golden edges and incredibly soft, chewy centers packed with melted chips.",
        ingredients: ["1 cup unsalted butter, softened", "3/4 cup brown sugar", "3/4 cup white sugar", "2 large eggs", "1 tsp vanilla extract", "2.25 cups all-purpose flour", "1 tsp baking soda", "1.5 cups semi-sweet chocolate chips"],
        directions: ["Preheat oven to 375°F (190°C) and line a sheet with parchment paper.", "Cream together softened butter, brown sugar, and white sugar until fluffy.", "Beat in eggs one at a time, then mix in the vanilla extract.", "Fold in flour and baking soda until combined, then fold in chocolate chips.", "Drop rounded tablespoons of dough onto sheet and bake for 9-11 minutes."]
    },
    {
        id: "tropical-smoothie",
        title: "Sunset Tropical Smoothie",
        category: "Drinks",
        img: "https://images.unsplash.com/photo-1553530666-ba11a7da3888",
        url: "recipe-details.html?id=tropical-smoothie",
        reviews: "55",
        description: "A bright, refreshing escape in a glass made from blended mango, pineapple, strawberries, and splash of coconut milk.",
        ingredients: ["1 cup frozen mango chunks", "1 cup frozen pineapple chunks", "1/2 cup fresh strawberries", "1 cup light coconut milk", "1 banana, sliced"],
        directions: ["Pour light coconut milk into the base of a high-speed blender.", "Add sliced banana, frozen mango, pineapple, and strawberry pieces.", "Blend on HIGH for 60 seconds until completely smooth.", "Pour into a glass and serve immediately."]
    },
    {
        id: "classic-meatloaf",
        title: "Grandma's Glazed Meatloaf",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1514516345957-556ca7d90a29",
        url: "recipe-details.html?id=classic-meatloaf",
        reviews: "185",
        description: "Comfort food at its finest—perfectly seasoned ground beef meatloaf brushed with a sweet, tangy ketchup and brown sugar glaze.",
        ingredients: ["2 lbs ground beef (80/20)", "1 cup breadcrumbs", "1/2 cup whole milk", "2 eggs, beaten", "1 small onion, minced", "1/2 cup ketchup (divided)", "2 tbsp brown sugar", "1 tbsp Worcestershire sauce"],
        directions: ["Preheat oven to 350°F (177°C) and grease a 9x5 inch loaf pan.", "Mix beef, breadcrumbs, milk, eggs, onion, Worcestershire, and 1/4 cup ketchup.", "Press mixture into the loaf pan evenly.", "Mix remaining 1/4 cup ketchup with brown sugar and brush over the top.", "Bake for 1 hour until internal temp is 160°F. Rest 10 minutes before slicing."]
    },
    {
        id: "fluffy-pancakes",
        title: "Buttermilk Fluffy Pancakes",
        category: "Breakfast",
        img: "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
        url: "recipe-details.html?id=fluffy-pancakes",
        reviews: "295",
        description: "Light, thick, and ultra-fluffy diner-style buttermilk pancakes made completely from scratch for the ultimate weekend breakfast.",
        ingredients: ["2 cups all-purpose flour", "3 tbsp sugar", "2 tsp baking powder", "1 tsp baking soda", "1/2 tsp salt", "2 cups buttermilk", "2 large eggs", "1/4 cup unsalted butter, melted"],
        directions: ["Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.", "In a separate bowl, whisk buttermilk, eggs, and melted butter.", "Combine wet and dry ingredients; stir gently until just combined (leave lumps).", "Pour 1/4 cup batter per pancake onto a hot, greased griddle.", "Cook until bubbles form on top, flip, and cook until golden brown."]
    },
    {
        id: "classic-lasagna",
        title: "Four-Cheese Italian Lasagna",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3",
        url: "recipe-details.html?id=classic-lasagna",
        reviews: "150",
        description: "Layers of seasoned rich meat sauce, lasagna noodles, creamy ricotta, and molten mozzarella baked to bubbly perfection.",
        ingredients: ["12 lasagna noodles, boiled", "1 lb Italian sausage", "1 jar (24 oz) marinara sauce", "1 container (15 oz) ricotta cheese", "1 egg", "3 cups shredded mozzarella", "1/2 cup parmesan cheese"],
        directions: ["Preheat oven to 375°F (190°C). Brown meat, drain, and stir in marinara.", "Mix ricotta cheese with the egg and half of the parmesan cheese.", "Layer 1/3 meat sauce, 4 noodles, 1/2 ricotta mixture, and 1 cup mozzarella in 9x13 dish.", "Repeat layers, ending with sauce and remaining mozzarella/parm.", "Cover with foil; bake 25 mins. Remove foil; bake another 20 mins."]
    },
    {
        id: "bbq-pulled-pork",
        title: "Slow Cooker BBQ Pulled Pork",
        category: "Slow Cooker",
        img: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd",
        url: "recipe-details.html?id=bbq-pulled-pork",
        reviews: "174",
        description: "Smoky, tender pulled pork shoulder slow-simmered and tossed in a sweet and tangy barbecue sauce layer.",
        ingredients: ["4 lb pork shoulder roast", "2 cups BBQ sauce", "1/2 cup apple cider vinegar", "1/2 cup chicken broth", "1 tbsp brown sugar", "1 tbsp paprika", "1 tsp garlic powder"],
        directions: ["Rub pork shoulder with brown sugar, paprika, and garlic powder.", "Place pork in slow cooker, add apple cider vinegar and chicken broth.", "Cover and cook on LOW for 8 hours until completely shreddable.", "Remove pork, shred with two forks, discard excess fat, and toss back in with BBQ sauce."]
    },
    {
        id: "air-fryer-salmon",
        title: "Garlic Butter Air Fryer Salmon",
        category: "Air Fryer",
        img: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
        url: "recipe-details.html?id=air-fryer-salmon",
        reviews: "89",
        description: "Perfectly flakey salmon fillets with a golden garlic butter crust, cooked effortlessly in the air fryer.",
        ingredients: ["2 salmon fillets", "1 tbsp melted butter", "2 cloves garlic, minced", "1/2 lemon, juiced", "1/2 tsp dill", "Salt and pepper"],
        directions: ["Preheat your air fryer to 400°F (204°C).", "Pat salmon fillets dry and season with salt and pepper.", "Mix melted butter, minced garlic, and lemon juice; brush over salmon.", "Air fry for 7-9 minutes depending on thickness, until salmon flakes easily."]
    },
    {
        id: "caesar-salad",
        title: "Classic Grilled Chicken Caesar",
        category: "Healthy",
        img: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9",
        url: "recipe-details.html?id=caesar-salad",
        reviews: "112",
        description: "Crisp romaine lettuce tossed in creamy Caesar dressing, loaded with garlic croutons and juicy grilled chicken breast chunks.",
        ingredients: ["2 chicken breasts", "1 large bunch romaine lettuce, chopped", "1/2 cup Caesar dressing", "1/2 cup parmesan cheese shavings", "1 cup garlic croutons"],
        directions: ["Season chicken breasts with salt, pepper, and garlic powder, then grill completely.", "Slice the grilled chicken into thin strips.", "In a large bowl, toss romaine lettuce with Caesar dressing and parmesan cheese.", "Top with croutons and grilled chicken strips, then serve immediately."]
    },
    {
        id: "beef-tacos",
        title: "Easy Weeknight Beef Tacos",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47",
        url: "recipe-details.html?id=beef-tacos",
        reviews: "245",
        description: "Crispy taco shells stuffed with perfectly seasoned ground beef, shredded cheddar, crisp lettuce, and fresh tomatoes.",
        ingredients: ["1 lb ground beef", "1 packet taco seasoning", "12 hard taco shells", "1 cup shredded cheddar", "1 cup shredded lettuce", "1 tomato, diced"],
        directions: ["Brown ground beef in a skillet over medium-high heat; drain grease.", "Add taco seasoning packet and water according to packet; simmer 5 minutes.", "Warm taco shells in the oven at 350°F for 5 minutes.", "Assemble tacos by layering beef, cheddar cheese, lettuce, and diced tomatoes."]
    },
    {
        id: "baked-mac-cheese",
        title: "Southern Baked Macaroni and Cheese",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686",
        url: "recipe-details.html?id=baked-mac-cheese",
        reviews: "312",
        description: "Ultra-creamy macaroni base baked with a thick, golden blanket of melted sharp cheddar and monterey jack cheeses.",
        ingredients: ["16 oz elbow macaroni", "4 tbsp butter", "1/4 cup flour", "2.5 cups whole milk", "2 cups sharp cheddar, shredded", "2 cups monterey jack, shredded"],
        directions: ["Boil macaroni until al dente; drain and set aside.", "Melt butter in a pan, whisk in flour, then slowly add milk until thick.", "Stir in half of both cheeses until completely melted into a smooth sauce.", "Mix cheese sauce with macaroni, pour into a baking dish, and top with remaining cheese.", "Bake at 350°F for 20-25 minutes until bubbling and golden on top."]
    },
    {
        id: "chicken-noodle-soup",
        title: "Homestyle Chicken Noodle Soup",
        category: "Soups",
        img: "https://images.unsplash.com/photo-1602253057119-44d745d9b860",
        url: "recipe-details.html?id=chicken-noodle-soup",
        reviews: "143",
        description: "Nourishing chicken broth loaded with tender shredded chicken, thick egg noodles, carrots, and celery stalks.",
        ingredients: ["2 cups shredded cooked chicken", "6 cups chicken broth", "2 cups wide egg noodles", "3 carrots, sliced", "3 celery stalks, sliced", "1/2 onion, diced"],
        directions: ["Sauté onions, carrots, and celery in a large pot with a splash of oil until soft.", "Pour in chicken broth and bring to a boil.", "Add wide egg noodles and cook for 8 minutes until tender.", "Stir in shredded chicken and simmer for an additional 5 minutes before serving."]
    },
    {
        id: "french-toast",
        title: "Classic Brioche French Toast",
        category: "Breakfast",
        img: "https://images.unsplash.com/photo-1484723091739-30a097e8f929",
        url: "recipe-details.html?id=french-toast",
        reviews: "167",
        description: "Thick slices of rich brioche bread soaked in a spiced egg custard and griddled to golden-brown perfection.",
        ingredients: ["1 loaf brioche bread, sliced thick", "4 large eggs", "1 cup whole milk", "1 tbsp cinnamon", "1 tsp vanilla extract", "Butter for griddle"],
        directions: ["Whisk eggs, milk, cinnamon, and vanilla together in a shallow dish.", "Melt a pat of butter on a skillet over medium heat.", "Dip bread slices into egg mixture for 10 seconds per side.", "Cook slices on skillet for 3-4 minutes per side until beautifully browned."]
    },
    {
        id: "fudgy-brownies",
        title: "Ultimate Fudgy Brownies",
        category: "Desserts",
        img: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c",
        url: "recipe-details.html?id=fudgy-brownies",
        reviews: "289",
        description: "Rich, dense, chocolatey brownies with an ultra-fudgy center and that perfect crinkly paper-thin top crust.",
        ingredients: ["1 cup melted butter", "2 cups sugar", "4 eggs", "1 cup cocoa powder", "1 cup all-purpose flour", "1 cup chocolate chunks"],
        directions: ["Preheat oven to 350°F (177°C) and grease a 9x13 baking pan.", "Whisk melted butter and sugar together, then beat in eggs one by one.", "Sift in cocoa powder and flour, folding gently until just incorporated.", "Fold in chocolate chunks, spread into pan, and bake for 22-25 minutes."]
    },
    {
        id: "strawberry-margarita",
        title: "Fresh Strawberry Margarita",
        category: "Drinks",
        img: "https://images.unsplash.com/photo-1556855248-7128e75f29f4",
        url: "recipe-details.html?id=strawberry-margarita",
        reviews: "73",
        description: "A frosty, vibrant blend of fresh sweet strawberries, lime juice, silver tequila, and a touch of agave nectar.",
        ingredients: ["1 cup fresh strawberries, hulled", "2 oz silver tequila", "1 oz triple sec", "1 oz fresh lime juice", "1 tbsp agave nectar", "Ice"],
        directions: ["Add strawberries, tequila, triple sec, lime juice, and agave to a blender.", "Fill blender with ice up to the liquid line.", "Blend on high until completely slushy and uniform.", "Pour into a salt-rimmed or sugar-rimmed glass and garnish with a lime wheel."]
    },
    {
        id: "greek-yogurt-parfait",
        title: "Berry Greek Yogurt Parfait",
        category: "Healthy",
        img: "https://images.unsplash.com/photo-1488477181946-6428a0291777",
        url: "recipe-details.html?id=greek-yogurt-parfait",
        reviews: "49",
        description: "Layers of thick vanilla Greek yogurt, crunchy honey granola, and a mix of fresh blueberries and raspberries.",
        ingredients: ["2 cups vanilla Greek yogurt", "1 cup honey almond granola", "1/2 cup fresh blueberries", "1/2 cup fresh raspberries", "2 tbsp honey"],
        directions: ["Grab two clear serving glasses or jars.", "Drop a layer of Greek yogurt into the bottom of each glass.", "Follow with a layer of granola, then a layer of mixed fresh berries.", "Repeat layers until glass is full, then drizzle honey over the top."]
    },
    {
        id: "air-fryer-french-fries",
        title: "Air Fryer Garlic Parmesan Fries",
        category: "Air Fryer",
        img: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
        url: "recipe-details.html?id=air-fryer-french-fries",
        reviews: "156",
        description: "Crispy, golden potato fries made with minimal oil, tossed in freshly grated parmesan cheese and garlic salt.",
        ingredients: ["3 russet potatoes, cut into matchsticks", "1 tbsp olive oil", "1 tsp garlic salt", "1/4 cup parmesan cheese, grated", "1 tbsp fresh parsley, chopped"],
        directions: ["Soak potato matchsticks in cold water for 30 minutes, then pat completely dry.", "Toss dried potatoes with olive oil and garlic salt in a large bowl.", "Place in air fryer basket and cook at 380°F for 20 minutes, shaking every 5 minutes.", "Increase temp to 400°F for 3 more minutes, then toss immediately with parmesan and parsley."]
    },
    {
        id: "slow-cooker-chili",
        title: "Hearty Slow Cooker Beef Chili",
        category: "Slow Cooker",
        img: "https://images.unsplash.com/photo-1541832676-9b763b0239ab",
        url: "recipe-details.html?id=slow-cooker-chili",
        reviews: "204",
        description: "A thick, classic chili packed with ground beef, kidney beans, diced tomatoes, and a robust blend of warming spices.",
        ingredients: ["2 lbs ground beef", "1 onion, diced", "2 cans kidney beans, drained", "2 cans diced tomatoes", "1 can tomato paste", "3 tbsp chili powder", "1 tbsp cumin"],
        directions: ["Brown ground beef and diced onions in a skillet; drain grease thoroughly.", "Transfer meat and onions into the base of your slow cooker.", "Add kidney beans, diced tomatoes, tomato paste, chili powder, and cumin.", "Stir well, cover, and cook on LOW for 6-8 hours until flavors are deep."]
    },
    {
        id: "lemon-lentil-soup",
        title: "Mediterranean Lemon Lentil Soup",
        category: "Soups",
        img: "https://images.unsplash.com/photo-1547592180-85f173990554",
        url: "recipe-details.html?id=lemon-lentil-soup",
        reviews: "82",
        description: "A hearty, plant-based soup featuring brown lentils, aromatic vegetables, and a bright finish of fresh lemon juice.",
        ingredients: ["1.5 cups brown lentils, rinsed", "1 onion, chopped", "2 carrots, diced", "4 cups vegetable broth", "1 lemon, juiced", "2 cups fresh spinach", "1 tsp cumin"],
        directions: ["Sauté onions and carrots in a deep pot until slightly softened.", "Add lentils, cumin, and vegetable broth; bring to a rolling boil.", "Reduce heat to low, cover, and simmer for 30 minutes until lentils are soft.", "Stir in fresh spinach and lemon juice right before turning off heat."]
    },
    {
        id: "shrimp-scampi",
        title: "Garlic Butter Shrimp Scampi",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1625938146369-adc83368bda7",
        url: "recipe-details.html?id=shrimp-scampi",
        reviews: "119",
        description: "Plump, tender shrimp sautéed in a rich garlic, white wine, and butter sauce, tossed with a bed of angel hair pasta.",
        ingredients: ["1 lb large shrimp, peeled and deveined", "8 oz angel hair pasta", "4 tbsp butter", "2 tbsp olive oil", "4 cloves garlic, minced", "1/4 cup white wine", "1/2 lemon, juiced"],
        directions: ["Boil angel hair pasta according to box instructions; drain.", "Melt butter and olive oil in a skillet over medium heat; add garlic and cook 1 minute.", "Add shrimp to pan and cook for 2 minutes per side until pink.", "Pour in white wine and lemon juice, let simmer 1 minute, then toss in pasta."]
    },
    {
        id: "banana-bread",
        title: "Classic Moist Banana Bread",
        category: "Desserts",
        img: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa",
        url: "recipe-details.html?id=banana-bread",
        reviews: "412",
        description: "The absolute best way to use overripe bananas: an incredibly moist, sweet loaf with a rich caramel notes.",
        ingredients: ["3 overripe bananas, mashed", "1/3 cup butter, melted", "3/4 cup sugar", "1 egg, beaten", "1 tsp vanilla extract", "1.5 cups all-purpose flour", "1 tsp baking soda", "Pinch of salt"],
        directions: ["Preheat your oven to 350°F (177°C) and grease a 4x8 inch loaf pan.", "In a large bowl, mash the bananas completely using a fork.", "Stir the melted butter directly into the mashed bananas.", "Mix in the sugar, beaten egg, and vanilla extract until well blended.", "Sprinkle in flour, baking soda, and salt; stir gently just until mixed, then bake for 50 minutes."]
    }
{
        id: "blueberry-muffins",
        title: "Bakery-Style Blueberry Muffins",
        category: "Desserts",
        img: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa",
        url: "recipe-details.html?id=blueberry-muffins",
        reviews: "188",
        description: "Tall, fluffy muffins bursting with juicy blueberries and finished with a crunchy sparkling sugar top.",
        ingredients: ["2 cups all-purpose flour", "1 cup granulated sugar", "2 tsp baking powder", "1/2 cup unsalted butter, melted", "2 large eggs", "1/2 cup milk", "1.5 cups fresh blueberries"],
        directions: ["Preheat oven to 400°F (204°C) and line a 12-cup muffin tin.", "Whisk flour, sugar, and baking powder together in a large bowl.", "In another bowl, blend melted butter, eggs, and milk.", "Fold wet ingredients into dry, then gently fold in blueberries.", "Divide into muffin cups and bake for 18-20 minutes until golden."]
    },
    {
        id: "slow-cooker-pulled-chicken",
        title: "Slow Cooker BBQ Pulled Chicken",
        category: "Slow Cooker",
        img: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd",
        url: "recipe-details.html?id=slow-cooker-pulled-chicken",
        reviews: "94",
        description: "Tender, juicy shredded chicken breasts slow-cooked in sweet barbecue sauce and perfect for piling onto brioche buns.",
        ingredients: ["2 lbs boneless chicken breasts", "1.5 cups sweet BBQ sauce", "1/4 cup apple cider vinegar", "1 tbsp brown sugar", "1 tsp garlic powder"],
        directions: ["Place chicken breasts into the bottom of the slow cooker.", "Whisk BBQ sauce, apple cider vinegar, brown sugar, and garlic powder together.", "Pour sauce over chicken, cover, and cook on LOW for 6 hours.", "Shred chicken with two forks directly in the slow cooker, mixing well with the sauce."]
    },
    {
        id: "air-fryer-pork-chops",
        title: "Juicy Air Fryer Pork Chops",
        category: "Air Fryer",
        img: "https://images.unsplash.com/photo-1606755962773-d324e0a13086",
        url: "recipe-details.html?id=air-fryer-pork-chops",
        reviews: "103",
        description: "Perfectly seasoned, thick-cut pork chops cooked in the air fryer to lock in all the juices with a beautiful outer crust.",
        ingredients: ["2 thick-cut bone-in pork chops", "1 tbsp olive oil", "1 tsp paprika", "1 tsp garlic powder", "1/2 tsp onion powder", "Salt and pepper"],
        directions: ["Preheat air fryer to 375°F (190°C).", "Rub pork chops on both sides with olive oil.", "Mix seasonings in a small dish and press firmly into the pork chops.", "Air fry for 10-12 minutes, flipping halfway through, until internal temp reaches 145°F."]
    },
    {
        id: "avocado-toast",
        title: "Ultimate Loaded Avocado Toast",
        category: "Healthy",
        img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        url: "recipe-details.html?id=avocado-toast",
        reviews: "76",
        description: "Thick sourdough toast layered with creamy mashed avocado, red pepper flakes, microgreens, and a soft-boiled egg.",
        ingredients: ["2 slices thick sourdough bread", "1 ripe avocado", "1 tsp lemon juice", "1/2 tsp red pepper flakes", "2 eggs", "Everything bagel seasoning"],
        directions: ["Toast sourdough bread slices until golden and crispy.", "Mash avocado with lemon juice, salt, and pepper in a small bowl.", "Boil eggs for 6 minutes, then plunge into ice water and peel.", "Spread avocado over toast, top with sliced boiled eggs, red pepper flakes, and seasoning."]
    },
    {
        id: "beef-stir-fry",
        title: "Quick Garlic Beef Stir-Fry",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1514516345957-556ca7d90a29",
        url: "recipe-details.html?id=beef-stir-fry",
        reviews: "142",
        description: "Flank steak strips flashed in a smoking hot wok with crisp broccoli florets and a savory brown ginger sauce.",
        ingredients: ["1 lb flank steak, thinly sliced", "2 cups broccoli florets", "1/3 cup soy sauce", "2 tbsp brown sugar", "1 tbsp minced ginger", "3 cloves garlic, minced"],
        directions: ["Whisk soy sauce, brown sugar, ginger, and garlic in a small bowl.", "Sear steak strips in a hot skillet with oil for 2-3 minutes until browned; set aside.", "Add broccoli to the same skillet with a splash of water; steam for 3 minutes.", "Return beef to pan, pour in sauce, and toss over high heat until sticky and bubbling."]
    },
    {
        id: "chicken-alfredo",
        title: "Creamy Chicken Fettuccine Alfredo",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3",
        url: "recipe-details.html?id=chicken-alfredo",
        reviews: "215",
        description: "Rich, velvety homemade parmesan cream sauce tossed with fettuccine pasta and topped with juicy sliced chicken breasts.",
        ingredients: ["8 oz fettuccine pasta", "2 chicken breasts", "1 cup heavy cream", "4 tbsp butter", "1 cup freshly grated parmesan cheese", "2 cloves garlic, minced"],
        directions: ["Cook fettuccine according to package instructions; drain.", "Season chicken breasts with salt and pepper; cook in a skillet until done, then slice.", "In the same skillet, melt butter and sauté garlic for 1 minute.", "Pour in heavy cream, bring to a simmer, stir in parmesan until smooth, then toss with pasta and chicken."]
    },
    {
        id: "iced-caramel-macchiato",
        title: "Café Iced Caramel Macchiato",
        category: "Drinks",
        img: "https://images.unsplash.com/photo-1553530666-ba11a7da3888",
        url: "recipe-details.html?id=iced-caramel-macchiato",
        reviews: "83",
        description: "A beautifully layered espresso drink with cold milk, sweet vanilla syrup, and a heavy drizzle of buttery caramel sauce.",
        ingredients: ["2 shots hot espresso", "1 cup whole milk", "1 tbsp vanilla syrup", "2 tbsp caramel sauce", "Ice"],
        directions: ["Add vanilla syrup to the bottom of a tall serving glass.", "Fill the glass to the top with ice cubes.", "Pour milk over the ice, leaving an inch of space at the top.", "Pour the hot espresso shots slowly over the ice to layer, then drizzle caramel over the top."]
    },
    {
        id: "chicken-parmesan",
        title: "Classic Crispy Chicken Parmesan",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
        url: "recipe-details.html?id=chicken-parmesan",
        reviews: "196",
        description: "Breaded, pan-fried chicken cutlets baked under a rich blanket of marinara sauce and melted fresh mozzarella cheese.",
        ingredients: ["2 chicken breasts, halved into cutlets", "1 cup Italian breadcrumbs", "1/2 cup grated parmesan", "2 eggs, beaten", "1 cup marinara sauce", "1 cup shredded mozzarella"],
        directions: ["Mix breadcrumbs and parmesan cheese together in a shallow dish.", "Dip chicken cutlets into beaten eggs, then press firmly into breadcrumbs.", "Pan-fry cutlets in olive oil for 4 minutes per side until crispy and golden.", "Place cutlets in a baking dish, top with marinara and mozzarella, and bake at 400°F for 10 minutes."]
    },
    {
        id: "waffles",
        title: "Crispy Golden Belgian Waffles",
        category: "Breakfast",
        img: "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
        url: "recipe-details.html?id=waffles",
        reviews: "154",
        description: "Light and airy waffles with a perfectly crisp exterior and deep pockets ready to catch warm maple syrup.",
        ingredients: ["2 cups all-purpose flour", "1 tsp baking powder", "1/2 tsp salt", "1/4 cup sugar", "2 eggs, separated", "1.75 cups milk", "1/2 cup vegetable oil"],
        directions: ["Preheat your Belgian waffle iron.", "Mix flour, baking powder, salt, and sugar together in a large bowl.", "Whisk egg yolks, milk, and vegetable oil together; stir into dry ingredients.", "Beat egg whites until stiff peaks form, then gently fold into batter.", "Pour onto hot waffle iron and cook according to manufacturer instructions."]
    },
    {
        id: "potato-leek-soup",
        title: "Classic Potato Leek Soup",
        category: "Soups",
        img: "https://images.unsplash.com/photo-1547592165-e1d17fed6005",
        url: "recipe-details.html?id=potato-leek-soup",
        reviews: "67",
        description: "A smooth, comforting, and velvety soup highlighting sweet leeks and russet potatoes simmered in vegetable broth.",
        ingredients: ["3 large leeks, white parts sliced", "2 lbs russet potatoes, peeled and diced", "4 tbsp butter", "4 cups vegetable broth", "1/2 cup heavy cream", "Salt and pepper"],
        directions: ["Melt butter in a large pot; cook sliced leeks for 8-10 minutes until very soft.", "Add diced potatoes and vegetable broth to the pot; bring to a boil.", "Reduce heat, cover, and simmer for 20 minutes until potatoes are completely tender.", "Puree with an immersion blender until completely silky, then stir in heavy cream."]
    },
    {
        id: "garlic-parmesan-wings",
        title: "Air Fryer Garlic Parmesan Wings",
        category: "Air Fryer",
        img: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877",
        url: "recipe-details.html?id=garlic-parmesan-wings",
        reviews: "148",
        description: "Crispy chicken wings tossed in a rich, savory coating of melted butter, minced garlic, and aged parmesan cheese.",
        ingredients: ["2 lbs chicken wings, patted dry", "1 tbsp baking powder", "1/2 tsp salt", "4 tbsp butter, melted", "3 cloves garlic, minced", "1/4 cup shredded parmesan"],
        directions: ["Toss dry wings with baking powder and salt until lightly coated.", "Arrange wings in a single layer inside the air fryer basket.", "Cook at 380°F for 20 minutes, flipping halfway through.", "Increase temp to 400°F for 5 more minutes, then toss immediately in combined garlic butter and parmesan."]
    },
    {
        id: "shrimp-tacos",
        title: "Cilantro Lime Shrimp Tacos",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47",
        url: "recipe-details.html?id=shrimp-tacos",
        reviews: "116",
        description: "Zesty, spice-rubbed grilled shrimp packed into warm corn tortillas with crunchy cabbage slaw and cilantro lime crema.",
        ingredients: ["1 lb medium shrimp, peeled", "1 tsp chili powder", "8 corn tortillas", "2 cups shredded cabbage", "1/4 cup sour cream", "1 lime, juiced"],
        directions: ["Toss shrimp with chili powder, cumin, salt, and oil; sear in a skillet for 2 minutes per side.", "Whisk sour cream and lime juice together to make the crema.", "Warm corn tortillas on a dry skillet until pliable.", "Assemble by layering shrimp and cabbage into tortillas, then drizzle with crema."]
    },
    {
        id: "slow-cooker-beef-stew",
        title: "Old-Fashioned Slow Cooker Beef Stew",
        category: "Slow Cooker",
        img: "https://images.unsplash.com/photo-1544025162-d76694265947",
        url: "recipe-details.html?id=slow-cooker-beef-stew",
        reviews: "182",
        description: "Rich, deeply flavored beef stew packed with tender chunks of beef, celery, carrots, and peas cooked low and slow.",
        ingredients: ["2 lbs beef stew meat, cubed", "1/3 cup flour", "3 russet potatoes, cubed", "4 carrots, sliced", "3 cups beef broth", "1 cup frozen peas", "1 tbsp Worcestershire sauce"],
        directions: ["Toss beef cubes in flour, salt, and pepper, then sear in a skillet until browned.", "Transfer beef to slow cooker along with cubed potatoes and sliced carrots.", "Pour in beef broth and Worcestershire sauce; stir well.", "Cover and cook on LOW for 7-8 hours, stirring in frozen peas during the last 20 minutes."]
    },
    {
        id: "quinoa-salad",
        title: "Mediterranean Quinoa Salad",
        category: "Healthy",
        img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        url: "recipe-details.html?id=quinoa-salad",
        reviews: "62",
        description: "A colorful, nutrient-dense cold salad filled with fluffy quinoa, crisp cucumbers, cherry tomatoes, Kalamata olives, and feta.",
        ingredients: ["1 cup quinoa, cooked and cooled", "1 cup cherry tomatoes, halved", "1 cucumber, diced", "1/2 cup Kalamata olives, pitted", "1/2 cup crumbled feta cheese", "3 tbsp olive oil"],
        directions: ["In a large bowl, combine the cooled quinoa, tomatoes, cucumber, and olives.", "Drizzle with olive oil and a squeeze of fresh lemon juice.", "Gently fold in the crumbled feta cheese.", "Chill in the refrigerator for 30 minutes before serving cold."]
    },
    {
        id: "chicken-quesadillas",
        title: "Cheesy Sheet Pan Chicken Quesadillas",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
        url: "recipe-details.html?id=chicken-quesadillas",
        reviews: "124",
        description: "An easy family favorite: crispy baked flour tortillas stuffed with seasoned shredded chicken and molten Mexican cheese blend.",
        ingredients: ["2 cups shredded cooked chicken", "1 packet taco seasoning", "4 large flour tortillas", "2 cups shredded Mexican cheese blend", "1 tbsp melted butter"],
        directions: ["Toss shredded chicken with taco seasoning and 2 tablespoons of water.", "Lay tortillas flat, filling half of each with chicken and cheese.", "Fold tortillas in half and place onto a lightly greased sheet pan.", "Brush tops with melted butter and bake at 400°F for 12-15 minutes until crispy."]
    },
    {
        id: "apple-crisp",
        title: "Warm Cinnamon Apple Crisp",
        category: "Desserts",
        img: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c",
        url: "recipe-details.html?id=apple-crisp",
        reviews: "203",
        description: "Sweet, spiced baked apples nestled under a thick, buttery cinnamon oat crumble layer.",
        ingredients: ["6 granny smith apples, peeled and sliced", "1 tbsp cinnamon", "1 cup rolled oats", "1/2 cup brown sugar", "1/2 cup all-purpose flour", "1/2 cup cold butter, cubed"],
        directions: ["Preheat oven to 350°F (177°C) and grease an 8x8 inch baking dish.", "Toss sliced apples with cinnamon and a tablespoon of sugar; place into dish.", "Mix oats, brown sugar, flour, and cold butter cubes with your fingers until crumbly.", "Scatter crumble evenly over the apples and bake for 35-40 minutes until bubbling."]
    },
    {
        id: "classic-mojito",
        title: "Fresh Mint Classic Mojito",
        category: "Drinks",
        img: "https://images.unsplash.com/photo-1556855248-7128e75f29f4",
        url: "recipe-details.html?id=classic-mojito",
        reviews: "92",
        description: "Crisp and incredibly refreshing, combining muddled fresh mint leaves, white rum, lime juice, and sparkling club soda.",
        ingredients: ["10 fresh mint leaves", "1/2 lime, cut into wedges", "2 tbsp white sugar", "2 oz white rum", "1/2 cup club soda", "Crushed ice"],
        directions: ["Muddle mint leaves, lime wedges, and white sugar in the bottom of a sturdy glass.", "Fill glass nearly to the top with crushed ice.", "Pour in the white rum and stir thoroughly to bring sugar up from bottom.", "Top off with club soda and garnish with a fresh mint sprig."]
    },
    {
        id: "eggs-benedict",
        title: "Classic Eggs Benedict",
        category: "Breakfast",
        img: "https://images.unsplash.com/photo-1484723091739-30a097e8f929",
        url: "recipe-details.html?id=eggs-benedict",
        reviews: "114",
        description: "Toasted English muffins topped with savory Canadian bacon, perfectly poached eggs, and warm, velvety hollandaise sauce.",
        ingredients: ["2 English muffins, split and toasted", "4 slices Canadian bacon", "4 large eggs (for poaching)", "3 egg yolks (for sauce)", "1/2 cup butter, melted", "1 tbsp lemon juice"],
        directions: ["Whisk egg yolks and lemon juice in a blender; slowly stream in hot melted butter until thick to make hollandaise.", "Poach 4 eggs in gently simmering water with a drop of vinegar for 3 minutes.", "Sear Canadian bacon in a skillet until warmed through.", "Layer toasted muffin halves with bacon, poached eggs, and a generous pour of hollandaise sauce."]
    },
    {
        id: "broccoli-cheddar-soup",
        title: "Creamy Broccoli Cheddar Soup",
        category: "Soups",
        img: "https://images.unsplash.com/photo-1602253057119-44d745d9b860",
        url: "recipe-details.html?id=broccoli-cheddar-soup",
        reviews: "235",
        description: "A rich, velvet-textured soup loaded with fresh broccoli florets and sharp cheddar cheese—just like your favorite bakery.",
        ingredients: ["2 cups broccoli florets, chopped small", "1 cup carrots, matchstick cut", "1/4 cup butter", "1/4 cup flour", "2 cups chicken broth", "2 cups sharp cheddar, shredded"],
        directions: ["Melt butter in a pot, whisk in flour, then gradually whisk in chicken broth until smooth.", "Add chopped broccoli and carrots; simmer over medium-low heat for 15 minutes.", "Turn heat to low and stir in shredded cheddar a handful at a time until completely smooth.", "Season with salt, pepper, and a pinch of nutmeg before serving."]
    },
    {
        id: "air-fryer-shrimp",
        title: "10-Minute Air Fryer Garlic Shrimp",
        category: "Air Fryer",
        img: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
        url: "recipe-details.html?id=air-fryer-shrimp",
        reviews: "77",
        description: "Plump, juicy shrimp seasoned with garlic, lemon, and a touch of paprika, cooked to perfection in just a few minutes.",
        ingredients: ["1 lb large shrimp, peeled and deveined", "1 tbsp olive oil", "1 tsp garlic powder", "1/2 tsp paprika", "1/2 lemon, sliced into wedges"],
        directions: ["Preheat your air fryer to 400°F (204°C).", "Toss the shrimp with olive oil, garlic powder, paprika, salt, and pepper.", "Arrange shrimp in a single layer inside the air fryer basket.", "Air fry for 5-6 minutes, shaking the basket halfway through, until pink and cooked through."]
    },
    {
        id: "slow-cooker-pork-carnitas",
        title: "Slow Cooker Crispy Pork Carnitas",
        category: "Slow Cooker",
        img: "https://images.unsplash.com/photo-1541832676-9b763b0239ab",
        url: "recipe-details.html?id=slow-cooker-pork-carnitas",
        reviews: "163",
        description: "Pork shoulder seasoned with citrus and Mexican spices, slow-cooked until tender, then broiled until edges are crispy.",
        ingredients: ["3 lb pork shoulder, cut into chunks", "1 orange, juiced", "1 lime, juiced", "4 cloves garlic, smashed", "1 tbsp cumin", "1 tbsp dried oregano"],
        directions: ["Place pork shoulder chunks into the slow cooker.", "Add orange juice, lime juice, smashed garlic, cumin, oregano, salt, and pepper; toss to coat.", "Cover and cook on LOW for 8 hours until completely tender.", "Shred meat, spread onto a baking sheet, and broil for 5-8 minutes until edges turn crispy."]
    },
    {
        id: "thai-peanut-noodles",
        title: "Spicy Thai Peanut Noodles",
        category: "Healthy",
        img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        url: "recipe-details.html?id=thai-peanut-noodles",
        reviews: "102",
        description: "A fast, comforting cold noodle salad tossed in a creamy, savory peanut butter, ginger, and sriracha sauce wrapper.",
        ingredients: ["8 oz spaghetti or lo mein noodles", "1/3 cup creamy peanut butter", "3 tbsp warm water", "2 tbsp soy sauce", "1 tbsp honey", "1 tsp sriracha"],
        directions: ["Boil noodles according to package instructions; drain and rinse with cold water.", "In a bowl, whisk peanut butter and warm water together until smooth.", "Whisk in soy sauce, honey, and sriracha until a creamy sauce forms.", "Pour peanut dressing over the cold noodles and toss well to coat entirely."]
    },
    {
        id: "shepherds-pie",
        title: "Classic Irish Shepherd's Pie",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1544025162-d76694265947",
        url: "recipe-details.html?id=shepherds-pie",
        reviews: "194",
        description: "Savory minced beef and vegetable gravy base layered underneath a thick blanket of fluffy, golden mashed potatoes.",
        ingredients: ["1 lb ground beef", "1 onion, diced", "1 cup frozen peas and carrots", "2 tbsp tomato paste", "1 cup beef broth", "3 cups prepared mashed potatoes"],
        directions: ["Brown ground beef and diced onion in a skillet; drain grease thoroughly.", "Stir in tomato paste, frozen peas and carrots, and beef broth; simmer 5 minutes.", "Pour beef mixture into an 8x8 inch baking dish.", "Spread mashed potatoes evenly over the top, then bake at 400°F for 20 minutes until golden."]
    },
    {
        id: "chicken-marsala",
        title: "Easy Skillet Chicken Marsala",
        category: "Dinner",
        img: "https://images.unsplash.com/photo-1602253057119-44d745d9b860",
        url: "recipe-details.html?id=chicken-marsala",
        reviews: "135",
        description: "Tender pan-seared chicken cutlets simmered in a rich, reduction sauce made of sweet Marsala wine and earthy cremini mushrooms.",
        ingredients: ["2 chicken breasts, halved into cutlets", "1/4 cup flour", "1 cup cremini mushrooms, sliced", "1/2 cup Marsala wine", "1/2 cup chicken broth", "4 tbsp butter"],
        directions: ["Dredge chicken cutlets lightly in flour seasoned with salt and pepper.", "Pan-sear chicken cutlets in 2 tablespoons of butter until golden; remove from pan.", "Add remaining butter and mushrooms to pan; sauté for 5 minutes.", "Pour in Marsala wine and chicken broth, simmer 3 minutes, return chicken, and cook until sauce thickens."]
    },
    {
        id: "peanut-butter-cups",
        title: "Homemade No-Bake Peanut Butter Cups",
        category: "Desserts",
        img: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e",
        url: "recipe-details.html?id=peanut-butter-cups",
        reviews: "212",
        description: "Better than store-bought! Simple layers of sweet peanut butter filling snapped inside a rich semi-sweet chocolate shell.",
        ingredients: ["2 cups semi-sweet chocolate chips", "1 cup creamy peanut butter", "1/2 cup powdered sugar", "4 tbsp butter, melted"],
        directions: ["Melt half of the chocolate chips and drop a spoonful into 12 paper muffin liners; chill 10 minutes.", "Mix peanut butter, powdered sugar, and melted butter together until smooth.", "Drop a spoonful of peanut butter mixture into each liner over the chocolate layer.", "Melt the rest of the chocolate, pour over the peanut butter layer, and freeze for 20 minutes."]
    }];
