const recipeCatalog = [
    { title: "Ramen Noodle Salad", category: "Salads", description: "Crunchy ramen noodles mixed with shredded cabbage, green onions, toasted almonds, and a sweet, tangy vinaigrette.", img: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600", reviews: "53", url: "#" },
    { title: "Perfect Baked Potato", category: "Side Dishes", description: "A classic steakhouse-style baked potato featuring crispy, salted skin and fluffy, pillowy insides.", img: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600", reviews: "1,415", url: "#" },
    { title: "Nathan's Exclusive New Hot Dog", category: "Fast Food", description: "Gourmet juicy hot dog grilled to snap-perfection and piled with rich, sweet caramelized onions.", img: "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=600", reviews: "34", url: "#" },
    { title: "Swamp Dogs Skillet", category: "Hot Dogs and Corn Dogs", description: "Sizzling skillet meal packed with smoked sausages, tri-color bell peppers, sweet yellow onions, and cajun spice.", img: "https://images.unsplash.com/photo-1541248421001-ecfc3bbf6e6f?w=600", reviews: "12", url: "#" },
    { title: "Mexican Street Corn Chicken Rice Bowl", category: "Bowls", description: "Vibrant and zesty grilled chicken served over fluffy rice, topped with cotija cheese, charred corn, lime juice, and cream.", img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600", reviews: "5", url: "#" },
    { title: "Za'atar Bean Salad", category: "Bean Salads", description: "A healthy, protein-packed array of tender garbanzo and white beans tossed with olive oil, herbs, and warm za'atar seasoning.", img: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600", reviews: "2", url: "#" },
    { title: "Beef Quesabirria Pizza", category: "Beef", description: "Slow-stewed, tender shredded beef birria spread across a crispy pizza crust with lots of melted cheese and consume dip.", img: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600", reviews: "1", url: "#" },
    { title: "Bigger Better Big Arch Burger", category: "Cheeseburger Recipes", description: "Double-stacked smash patties with crisp pickles, melty American cheese, onions, and our signature burger house dressing.", img: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600", reviews: "4", url: "#" },
    { title: "Easy Strawberry Shortcake", category: "Strawberry Shortcake Recipes", description: "Sweet buttermilk biscuits split wide open and loaded with fresh macerated summer strawberries and fresh whipped cream.", img: "https://images.unsplash.com/photo-1562376502-6f769499c886?w=600", reviews: "34", url: "#" },
    { title: "Amish Macaroni Salad", category: "Salad", description: "Classic sweet and tangy cold elbow macaroni salad mixed with hard-boiled eggs, crisp celery, and a rich creamy dressing.", img: "https://images.unsplash.com/photo-1621510456681-23a23cfb5f57?w=600", reviews: "1,415", url: "#" }
];
